"""Pydantic schemas package."""

from app.schemas.candidate_document import (
    CandidateDocumentCreate,
    CandidateDocumentRead,
    CandidateDocumentUpdate,
)
from app.schemas.candidate_profile import (
    CandidateAchievementCreate,
    CandidateAchievementRead,
    CandidateCertificationCreate,
    CandidateCertificationRead,
    CandidateEducationCreate,
    CandidateEducationRead,
    CandidateExperienceCreate,
    CandidateExperienceRead,
    CandidateProfileCreate,
    CandidateProfileRead,
    CandidateProfileUpdate,
    CandidateProjectCreate,
    CandidateProjectRead,
    CandidatePublicationCreate,
    CandidatePublicationRead,
    CandidateSkillCreate,
    CandidateSkillRead,
)
from app.schemas.cover_letter import (
    CoverLetterGenerationContext,
    GroundedCoverLetterParagraph,
    TailoredCoverLetterContent,
    TailoredCoverLetterDraft,
)
from app.schemas.job import JobCreate, JobIngestRequest, JobRead
from app.schemas.tailored_resume import (
    GroundedResumeStatement,
    ResumeGenerationContext,
    ResumeGroundingBundle,
    ResumeHeader,
    ResumeRequirementTrace,
    SelectedResumeEvidence,
    TailoredResumeContent,
    TailoredResumeDraft,
    TailoredResumeSection,
)
from app.schemas.tailored_resume_persistence import (
    TailoredResumeRead,
    TailoredResumeSummary,
)
from app.schemas.tailored_resume_record import (
    TailoredResumeRecordList,
    TailoredResumeRecordRead,
    TailoredResumeRecordSummary,
)

__all__ = [
    "CandidateAchievementCreate",
    "CandidateAchievementRead",
    "CandidateCertificationCreate",
    "CandidateCertificationRead",
    "CandidateDocumentCreate",
    "CandidateDocumentRead",
    "CandidateDocumentUpdate",
    "CandidateEducationCreate",
    "CandidateEducationRead",
    "CandidateExperienceCreate",
    "CandidateExperienceRead",
    "CandidateProfileCreate",
    "CandidateProfileRead",
    "CandidateProfileUpdate",
    "CandidateProjectCreate",
    "CandidateProjectRead",
    "CandidatePublicationCreate",
    "CandidatePublicationRead",
    "CandidateSkillCreate",
    "CandidateSkillRead",
    "CoverLetterGenerationContext",
    "GroundedCoverLetterParagraph",
    "JobCreate",
    "JobIngestRequest",
    "JobRead",
    "GroundedResumeStatement",
    "ResumeGroundingBundle",
    "ResumeGenerationContext",
    "ResumeHeader",
    "ResumeRequirementTrace",
    "SelectedResumeEvidence",
    "TailoredResumeDraft",
    "TailoredResumeContent",
    "TailoredResumeSection",
    "TailoredResumeRead",
    "TailoredResumeSummary",
    "TailoredResumeRecordList",
    "TailoredResumeRecordRead",
    "TailoredResumeRecordSummary",
    "TailoredCoverLetterContent",
    "TailoredCoverLetterDraft",
]
