# """add structured job requirements

# Revision ID: 8fe0e5d78fe7
# Revises: 20260824_000004
# Create Date: 2026-08-28 13:10:23.601172
# """

# from alembic import op
# import sqlalchemy as sa
# from sqlalchemy.dialects import postgresql

# # revision identifiers, used by Alembic.
# revision = '8fe0e5d78fe7'
# down_revision = '20260824_000004'
# branch_labels = None
# depends_on = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('job_requirements',
#     sa.Column('id', sa.UUID(), nullable=False),
#     sa.Column('job_id', sa.UUID(), nullable=False),
#     sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
#     sa.Column('preferred_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
#     sa.Column('required_experience', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
#     sa.Column('responsibilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
#     sa.Column('education_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
#     sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
#     sa.Column('domain_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
#     sa.Column('minimum_experience_years', sa.Float(), nullable=True),
#     sa.Column('provider', sa.String(), nullable=False),
#     sa.Column('model_name', sa.String(), nullable=False),
#     sa.Column('extraction_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
#     sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
#     sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_index(op.f('ix_job_requirements_job_id'), 'job_requirements', ['job_id'], unique=True)
#     # op.drop_index('ix_candidate_documents_profile_id', table_name='candidate_documents')
#     # op.drop_index('ix_candidate_evidence_evidence_type', table_name='candidate_evidence')
#     # op.drop_index('ix_candidate_evidence_profile_id', table_name='candidate_evidence')
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_index('ix_candidate_evidence_profile_id', 'candidate_evidence', ['profile_id'], unique=False)
#     op.create_index('ix_candidate_evidence_evidence_type', 'candidate_evidence', ['evidence_type'], unique=False)
#     op.create_index('ix_candidate_documents_profile_id', 'candidate_documents', ['profile_id'], unique=False)
#     op.drop_index(op.f('ix_job_requirements_job_id'), table_name='job_requirements')
#     op.drop_table('job_requirements')
#     # ### end Alembic commands ###

"""add structured job requirements

Revision ID: 8fe0e5d78fe7
Revises: 20260824_000004
Create Date: 2026-08-28 13:10:23.601172
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "8fe0e5d78fe7"
down_revision = "20260824_000004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "job_requirements",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "job_id",
            sa.UUID(),
            nullable=False,
        ),
        sa.Column(
            "required_skills",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "preferred_skills",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "required_experience",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "responsibilities",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "education_requirements",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "certifications",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "domain_keywords",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "minimum_experience_years",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "provider",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "model_name",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "extraction_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_job_requirements_job_id"),
        "job_requirements",
        ["job_id"],
        unique=True,
    )


def downgrade() -> None:
    op.drop_index(
        op.f("ix_job_requirements_job_id"),
        table_name="job_requirements",
    )

    op.drop_table("job_requirements")